services:
  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/ama
      PORT: "3000"
      ADMIN_KEY: ${ADMIN_KEY:-dev-admin-key-change-me}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  web:
    build: ./web
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: ama
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  pgdata:
