# Legacy CI file - replaced by ci.yaml
# This file is kept for reference but should not be used

# name: CI
# on:
#   push:
#   pull_request:

# jobs:
#   api-tests:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:16-alpine
#         env:
#           POSTGRES_USER: app
#           POSTGRES_PASSWORD: app
#           POSTGRES_DB: ama
#         ports: ["5432:5432"]
#         options: >-
#           --health-cmd="pg_isready -U app -d ama"
#           --health-interval=10s --health-timeout=5s --health-retries=5
#       redis:
#         image: redis:7-alpine
#         ports: ["6379:6379"]

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: npm
#           cache-dependency-path: api/package-lock.json
#       - run: npm ci
#         working-directory: api
#       - name: Push schema to ephemeral DB
#         run: npx prisma db push
#         working-directory: api
#         env:
#           DATABASE_URL: postgresql://app:app@localhost:5432/ama
#       - run: npm test -- --coverage
#         working-directory: api
#         env:
#           DATABASE_URL: postgresql://app:app@localhost:5432/ama
#           REDIS_URL: redis://localhost:6379
#       - uses: actions/upload-artifact@v4
#         with:
#           name: api-coverage
#           path: api/coverage
